openapi: 3.0.1
info:
  title: TODO Plugin
  description: A plugin that allows the user to create and manage a TODO list & Task list using ChatGPT.
  version: 'v1'
servers:
  - url: http://localhost:3000
paths:
  /api/todos:
    get:
      operationId: getTodos
      summary: Get the list of todos
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getTodosResponse'
  /api/create-todo:
    post:
      operationId: addTodo
      summary: add a new todo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/addTodoRequest'
      responses:
        "200":
          description: OK
  /tasks:
    get:
      operationId: getTasks
      summary: Get the list of tasks
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getTasksResponse'
  /create-task:
    post:
      operationId: addTask
      summary: add a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/addTaskRequest'
      responses:
        "200":
          description: OK
components:
  schemas:
    addTodoRequest:
      type: object
      required:
      - todo
      properties:
        todo:
          type: string
          description: The todo to add to the list.
          required: true
    getTodosResponse:
      type: object
      properties:
        todos:
          type: array
          items:
            type: string
          description: The list of todos.
    addTaskRequest:
      type: object
      required:
      - task
      properties:
        task:
          type: string
          description: The task to add to the list.
          required: true
    getTasksResponse:
      type: object
      properties:
        tasks:
          type: array
          items:
            type: string
          description: The list of tasks.